namespace Tomat.GameMaker.IFF.DataTypes.Models.Code;

public enum GameMakerCodeInstructionOpcode : byte {
    Conv     = 0x07,
    Mul      = 0x08,
    Div      = 0x09,
    Rem      = 0x0A,
    Mod      = 0x0B,
    Add      = 0x0C,
    Sub      = 0x0D,
    And      = 0x0E,
    Or       = 0x0F,
    Xor      = 0x10,
    Neg      = 0x11,
    Not      = 0x12,
    Shl      = 0x13,
    Shr      = 0x14,
    Cmp      = 0x15,
    Pop      = 0x45,
    Dup      = 0x86,
    Ret      = 0x9C,
    Exit     = 0x9D,
    Popz     = 0x9E,
    B        = 0xB6,
    Bt       = 0xB7,
    Bf       = 0xB8,
    PushEnv  = 0xBA,
    PopEnv   = 0xBB,
    Push     = 0xC0,
    PushLoc  = 0xC1,
    PushGlb  = 0xC2,
    PushBltn = 0xC3,
    PushI    = 0x84,
    Call     = 0xD9,
    CallV    = 0x99,
    Break    = 0xFF,
}
